#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetISTA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProjetISTA_1")]
	public partial class Add_venteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public Add_venteDataContext() : 
				base(global::ProjetISTA.Properties.Settings.Default.ProjetISTAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Add_venteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Add_venteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Add_venteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Add_venteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CMD_del1")]
		public int CMD_del1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_vente", DbType="Int")] System.Nullable<int> id_vente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_vente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CMD_Add1")]
		public int CMD_Add1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Cl", DbType="Int")] System.Nullable<int> id_Cl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Vd", DbType="NVarChar(50)")] string nom_Vd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prix", DbType="Money")] System.Nullable<decimal> prix, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DesCmd", DbType="Text")] string desCmd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateCmd", DbType="Date")] System.Nullable<System.DateTime> dateCmd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idproduit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantite", DbType="Int")] System.Nullable<int> quantite, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> totalvente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Cl, nom_Vd, prix, desCmd, dateCmd, idproduit, quantite, totalvente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CMD_Add2")]
		public int CMD_Add2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_Cl", DbType="Int")] System.Nullable<int> id_Cl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Vd", DbType="NVarChar(50)")] string nom_Vd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prix", DbType="Money")] System.Nullable<decimal> prix, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DesCmd", DbType="Text")] string desCmd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateCmd", DbType="Date")] System.Nullable<System.DateTime> dateCmd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idproduit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantite", DbType="Int")] System.Nullable<int> quantite, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> totalvente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sale", DbType="Text")] string sale)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_Cl, nom_Vd, prix, desCmd, dateCmd, idproduit, quantite, totalvente, sale);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
